### ISSUE TITLE
Bot offline

### ISSUE THREAD

**Issue by Sam1370** [inculi/Sue#14]
Could you give it a kick? Thanks

**Comment by Manwholikespie** [comment]
Dearest Sam1370, man of mystery, man of talent. I humbly apologize for the horrid nightmare of life you must be going through at this moment. I too dearly miss the beloved Sue. Soon she shall rise again. The hour of this resurrection depends when my home internet is back up. I commend your enduring faith.

Best regards,
The Dark Lord Robert™ (blessed be his name)

![1573006165045](https://user-images.githubusercontent.com/6274589/73402523-1e1cbb00-42b3-11ea-8581-3ec6c8d97cee.png)

**Comment by Sam1370** [comment]
Thank you! Haha

**Comment by Manwholikespie** [comment]
fin.
